### ISSUE TITLE
It should be in typescript, currently it does not support any typescript project

### ISSUE THREAD

**Issue by numandev1** [JijaProGamer/puppeteer-extra-plugin-fingerprinter#1]
if i use this package into typescript project this i am getting this error 
```
/Users/apple/project/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/apple/project/node_modules/puppeteer-extra-plugin-fingerprinter/index.js from /Users/apple/project/src/puppeteer-extra-plugin-fingerprinter.js not supported.
Instead change the require of index.js in /Users/apple/project/src/puppeteer-extra-plugin-fingerprinter.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by JijaProGamer** [comment]
Are you sure you imported correctly? This is how its done:

import { createFingerprinterInterface, commonFingerprint, generateFingerprint } from "puppeteer-extra-plugin-fingerprinter”

**Comment by numandev1** [comment]
@JijaProGamer i was importing same way but getting above error.

**Comment by JijaProGamer** [comment]
If your typescript compiler has no support for require thats its problem, there is no pollyfill for it and its needed for my module.

**Comment by numandev1** [comment]
> If your typescript compiler has no support for require thats its problem, there is no pollyfill for it and its needed for my module.

I think, it is possible with `webpack` but not possible with `ts-node`
