### ISSUE TITLE
Cannot compile an exe with pkg node with this library

### ISSUE THREAD

**Issue by MarioCodarin** [JijaProGamer/puppeteer-extra-plugin-fingerprinter#3]
Hello this library is awesome but i have a little problem if someone can solve it.
When i try to compile the exe i get this error
> Warning Babel parse has failed: import.meta may appear only with 'sourceType: "module"' (11:42)

i've tried to change to nexe but it doesn't work neither, how can i compile my exe?

**Comment by JijaProGamer** [comment]
Why would you want to compile a puppeteer-extra-plugin as an exe? Also, this is a Babel issue, not my script's issue.
